import flash.geom.ColorTransform;
import flash.geom.Transform;
intrinsic class com.Utils.Colors
{
	static public var e_ColorWhite : Number;
	static public var e_ColorBlack : Number;
	static public var e_ColorYellow : Number;
	static public var e_ColorRed : Number;
	static public var e_ColorDarkRed : Number;
	static public var e_ColorPureRed : Number;
	static public var e_ColorDarkBlue : Number;
	static public var e_ColorBlue : Number;
	static public var e_ColorLightBlue : Number;
	static public var e_ColorGreen : Number;
	static public var e_ColorDarkGreen : Number;
	static public var e_ColorPureGreen : Number;
	static public var e_ColorPureYellow : Number;
	static public var e_ColorSignalGreen : Number;
	static public var e_ColorLightGreen : Number;
	static public var e_ColorOrange : Number;
	static public var e_ColorDarkOrange : Number;
	static public var e_ColorLightOrange : Number;
	static public var e_ColorLightRed : Number;
	static public var e_ColorCyan : Number;
	static public var e_ColorMagenta : Number;
	static public var e_ColorPurple : Number;
	static public var e_ColorPalePurple : Number;
	static public var e_ColorDefaultBackground : Number;
	static public var e_ColorDefaultHighlight : Number;
	static public var e_ColorRangedSpellBackground : Number;
	static public var e_ColorRangedSpellHighlight : Number;
	static public var e_ColorMeleeSpellBackground : Number;
	static public var e_ColorMeleeSpellHighlight : Number;
	static public var e_ColorSupportSpellBackground : Number;
	static public var e_ColorSupportSpellHighlight : Number;
	static public var e_ColorHealSpellBackground : Number;
	static public var e_ColorHealSpellHighlight : Number;
	static public var e_ColorMagicSpellBackground : Number;
	static public var e_ColorMagicSpellHighlight : Number;
	static public var e_ColorPassiveSpellBackground : Number;
	static public var e_ColorPassiveSpellHighlight : Number;
	static public var e_ColorTrueBandBuffBackground : Number;
	static public var e_ColorTrueBandBuffHighlight : Number;
	static public var e_ColorOffensiveBuffBackground : Number;
	static public var e_ColorOffensiveBuffHighlight : Number;
	static public var e_ColorDefensiveBuffBackground : Number;
	static public var e_ColorDefensiveBuffHighlight : Number;
	static public var e_ColorHealBuffBackground : Number;
	static public var e_ColorHealBuffHighlight : Number;
	static public var e_ColorGenericBuffBackground : Number;
	static public var e_ColorGenericBuffHighlight : Number;
	static public var e_ColorAfflictedDebuffBackground : Number;
	static public var e_ColorAfflictedDebuffHighlight : Number;
	static public var e_ColorWeakenedDebuffBackground : Number;
	static public var e_ColorWeakenedDebuffHighlight : Number;
	static public var e_ColorHinderedDebuffBackground : Number;
	static public var e_ColorHinderedDebuffHighlight : Number;
	static public var e_ColorImpariedDebuffBackground : Number;
	static public var e_ColorImpariedDebuffHighlight : Number;
	static public var e_ColorFilthDebuffBackground : Number;
	static public var e_ColorFilthDebuffHighlight : Number;
	static public var e_ColorGenericDebuffBackground : Number;
	static public var e_ColorGenericDebuffHighlight : Number;
	static public var e_ColorWeaponItemsBackground : Number;
	static public var e_ColorWeaponItemsHightlight : Number;
	static public var e_ColorTalismanHeadBackground : Number;
	static public var e_ColorTalismanHeadHightlight : Number;
	static public var e_ColorTalismanMajorBackground : Number;
	static public var e_ColorTalismanMajorHightlight : Number;
	static public var e_ColorTalismanMinorBackground : Number;
	static public var e_ColorTalismanMinorHightlight : Number;
	static public var e_ColorCraftingItemsBackground : Number;
	static public var e_ColorCraftingItemsHighlight : Number;
	static public var e_ColorUnusableMissionItemsBackground : Number;
	static public var e_ColorUnusableMissionItemsHighlight : Number;
	static public var e_ColorUsableMissionItemsBackground : Number;
	static public var e_ColorUsableMissionItemsHighlight : Number;
	static public var e_ColorTrinketsBackground : Number;
	static public var e_ColorTrinketsHighlight : Number;
	static public var e_ColorConsumablesBackground : Number;
	static public var e_ColorConsumablesHighlight : Number;
	static public var e_ColorSocialConsumablesBackground : Number;
	static public var e_ColorSocialConsumablesHighlight : Number;
	static public var e_ColorClothingItemsBackground : Number;
	static public var e_ColorClothingItemsHighlight : Number;
	static public var e_ColorSilverBackground : Number;
	static public var e_ColorSilverHighlight : Number;
	static public var e_ColorChristmasBackground : Number;
	static public var e_ColorChristmasHighlight : Number;
	static public var e_ColorDamageAugmentBackground : Number;
	static public var e_ColorDamageAugmentHighlight : Number;
	static public var e_ColorHealingAugmentBackground : Number;
	static public var e_ColorHealingAugmentHighlight : Number;
	static public var e_ColorSurvivabilityAugmentBackground : Number;
	static public var e_ColorSurvivabilityAugmentHighlight : Number;
	static public var e_ColorSupportAugmentBackground : Number;
	static public var e_ColorSupportAugmentHighlight : Number;
	static public var e_ColorShieldAegisBackground : Number;
	static public var e_ColorShieldAegisHighlight : Number;
	static public var e_ColorBoosterAegisBackground : Number;
	static public var e_ColorBoosterAegisHighlight : Number;
	static public var e_ColorSpecialAegisBackground : Number;
	static public var e_ColorSpecialAegisHighlight : Number;
	static public var e_ColorWeaponAegisBackground : Number;
	static public var e_ColorWeaponAegisHighlight : Number;
	static public var e_ColorGoodUltimateBackground : Number;
	static public var e_ColorGoodUltimateHighlight : Number;
	static public var e_ColorNeutralUltimateBackground : Number;
	static public var e_ColorNeutralUltimateHighlight : Number;
	static public var e_ColorEvilUltimateBackground : Number;
	static public var e_ColorEvilUltimateHighlight : Number;
	static public var e_ColorMuseumItemBackground : Number;
	static public var e_ColorMuseumItemHighlight : Number;
	static public var e_ColorUniqueEquipmentBackground : Number;
	static public var e_ColorUniqueEquipmentHighlight : Number;
	static public var e_ColorCharcoal : Number;
	static public var e_ColorDarkGray : Number;
	static public var e_ColorGray : Number;
	static public var e_ColorCastbar : Number;
	static public var e_ColorDisabledAbility : Number;
	static public var e_ColorIconDefault : Number;
	static public var e_ColorIconRangedSpell : Number;
	static public var e_ColorIconMeleeSpell : Number;
	static public var e_ColorIconSupportSpell : Number;
	static public var e_ColorIconHealSpell : Number;
	static public var e_ColorIconMagicSpell : Number;
	static public var e_ColorIconPassiveSpell : Number;
	static public var e_ColorIconTrueBandBuff : Number;
	static public var e_ColorIconOffensiveBuff : Number;
	static public var e_ColorIconDefensiveBuff : Number;
	static public var e_ColorIconHealBuff : Number;
	static public var e_ColorIconGenericBuff : Number;
	static public var e_ColorIconAfflictedDebuff : Number;
	static public var e_ColorIconWeakenedDebuff : Number;
	static public var e_ColorIconHinderedDebuff : Number;
	static public var e_ColorIconImpariedDebuff : Number;
	static public var e_ColorIconFilthDebuff : Number;
	static public var e_ColorIconGenericDebuff : Number;
	static public var e_ColorBorderItemSuperior : Number;
	static public var e_ColorBorderItemEnchanted : Number;
	static public var e_ColorBorderItemRare : Number;
	static public var e_ColorBorderItemEpic : Number;
	static public var e_ColorBorderItemLegendary : Number;
	static public var e_ColorBorderItemRed : Number;
	static public var e_ColorBorderItemMission : Number;
	static public var e_ColorBorderItemMissionUsable : Number;
	static public var e_ColorItemTypeWeapons : Number;
	static public var e_ColorItemTypeCrafting : Number;
	static public var e_ColorItemTypeChakras : Number;
	static public var e_ColorItemTypeCenterChakra : Number;
	static public var e_ColorItemTypeConsumable : Number;
	static public var e_ColorItemTypeMissionUsable : Number;
	static public var e_ColorItemTypeMission : Number;
	static public var e_ColorItemUnusuable : Number;
	static public var e_ColorBuff : Number;
	static public var e_ColorDebuff : Number;
	static public var e_ColorStates : Number;
	static public var e_ColorDefaultToken : Number;
	static public var e_ColorHealthCritical : Number;
	static public var e_ColorHealthNormal : Number;
	static public var e_ColorAnimaCritical : Number;
	static public var e_ColorAnimaNormal : Number;
	static public var e_ColorMissionAction : Number;
	static public var e_ColorMissionInvestigation : Number;
	static public var e_ColorMissionSabotage : Number;
	static public var e_ColorMissionStory : Number;
	static public var e_ColorMissionDungeon : Number;
	static public var e_ColorMissionRaid : Number;
	static public var e_Equal : Number;
	static public var e_Moderate : Number;
	static public var e_Easy : Number;
	static public var e_Challenging : Number;
	static public var e_Demanding : Number;
	static public var e_Difficult : Number;
	static public var e_ColorPanelsBackground : Number;
	static public var e_ColorPanelsLine : Number;
	static public var e_ColorJournalMainTier : Number;
	static public var e_ColorJournalSubTier : Number;
	static public var e_ColorJournalRepetableFont : Number;
	static public var e_ColorJournalUnrepeatableFont : Number;
	static public var e_ColorTimeoutSuccess : Number;
	static public var e_ColorTimeoutFail : Number;
	static public var e_ColorEnabledIcon : Number;
	static public var e_ColorDisabledIcon : Number;
	static public var e_ColorPvPIlluminati : Number;
	static public var e_ColorPvPIlluminatiText : Number;
	static public var e_ColorPvPDragon : Number;
	static public var e_ColorPvPDragonText : Number;
	static public var e_ColorPvPTemplar : Number;
	static public var e_ColorPvPTemplarText : Number;
	static public var e_ColorDamage : Number;
	static public var e_ColorCompassLines : Number;

	static public function GetColorlineColors(colorline:Number) : Object;

	static public function GetColor(p_colorline:Number) : Number;

	static public function GetMissionColor(missionType);

	static public function GetNametagColor(nametagCategory:Number, aggroStanding:Number);

	static public function GetNametagIconColor(rankDifference:Number);

	static public function GetItemRarityColor(rarity:Number);

	static public function ColorToHtml(color:Number) : String;

	static public function ApplyColor(mc:MovieClip, color:Number);

	/**
	 * 
	 * @param	mc:MovieClip - the clip to ting
	 * @param	color - the color (hex)
	 * @param	amount - amount in percent (0 - 100)
	 */
	static public function Tint(mc:MovieClip, color:Number, amount:Number);

}